### ISSUE TITLE
Help to understand aa and dna identity score calculations

### ISSUE THREAD

**Issue by StromTroopers** [steineggerlab/Metabuli#16]
Dear Metabuli Developpers,

To test the sensibility of Metabuli, I recently tried to match DNAseq reads from a `Virus_A` (taxid : 552509) to another closely related `Virus_B` (not present in the refseq database) to see if Metabuli was able to discover new closely related viruses in metagenomic samples.

So I took the reads from the `Virus_B` (files called **VirusB_1.fastq** and **VirusB_2.fastq**) and I took as database your pre-built refseq_virus database from which the proteins of the `Virus_A` are present inside. 

Here is the code used : 

`metabuli classify VirusB_1.fastq VirusB_2.fastq  RefSeq_virus_db Virus_genome --threads 20`

In total, I successfully got `7074 hits`.

```
>>> tab
      Classified                                 Read_ID  Tax_id  Read_length  DNA_identity  AA_identity  Hamming_distance Classification_Rank List_taxID:k-mer_count
0              1   A00553:76:H5N52DSX2:2:1101:6497:10927  552509          294      0.117347     0.153061                 7             species              552509:8
1              1  A00553:76:H5N52DSX2:2:1101:14226:11162  552509          294      0.117347     0.153061                 7             species              552509:8
2              1  A00553:76:H5N52DSX2:2:1101:30969:16141  552509          294      0.107143     0.142857                 7             species              552509:7
3              1  A00553:76:H5N52DSX2:2:1101:22634:19711  552509          294      0.117347     0.153061                 7             species              552509:8
4              1   A00553:76:H5N52DSX2:2:1101:8603:30452  552509          294      0.102041     0.142857                 8             species              552509:7
...          ...                                     ...     ...          ...           ...          ...               ...                 ...                    ...
7069           1   A00553:76:H5N52DSX2:2:2678:7627:14982  552509          294      0.086735     0.112245                 5             species              552509:4
7070           1  A00553:76:H5N52DSX2:2:2678:24189:20212  552509          294      0.091837     0.122449                 6             species              552509:5
7071           1  A00553:76:H5N52DSX2:2:2678:32325:22060  552509          294      0.181973     0.244898                13             species             552509:10
7072           1  A00553:76:H5N52DSX2:2:2678:14299:28823  552509          294      0.117347     0.142857                 5             species              552509:7
7073           1  A00553:76:H5N52DSX2:2:2678:17969:33896  552509          294      0.102041     0.142857                 8             species              552509:7

[7074 rows x 9 columns]
```

So it means that Metabuli can successfully find in metagenomic data closely related viruses, which other soft such as Kraken2 cannot If I well understood (correct me if I'm wrong). However, the AA and DNA scores of identity really surprised me (**DNA mean identity =0.106** and **AA mean identity =0.136** over the 7074 hits). This is far less than expected between `Virus_A` and `Virus_B` where the average AA mean identity is 0.391 when you do a blastp of the `Virus_A` vs `Virus_B `genomes. 

I don't know if I am missing something and If it is clear. Could you please help me to understand the identity score calculation? 

All the best

**Comment by JaebeomKim0731** [comment]
Yes, Metabuli is more sensitive than DNA-based classification :)
Given the average scores, viruses A and B are quite distant.
I guess a much less number of reads will be classified as 552509 with DNA-based tools.

Here is the answer to your question.
Metabuli is using 8-mers of amino acid (AA) and searches for exact AA matches between query 8-mers and reference 8-mers. 
After finding all matches, matched 8-mers are aligned to each query read.
The read length, the number of matched amino acids, and DNA Hamming distance of the matched amino acids are used to calculate the scores.
```
AA identity = the number of matched amino acids * 3 / the read length
DNA identity = (the number of matched amino acids * 3 - DNA Hamming distance) / the read length
```
You can find more details in **Metabuli: Classification** section of Methods and **Supp. Fig. 2** in the paper. https://www.biorxiv.org/content/10.1101/2023.05.31.543018v1



And these scores tend to be lower than Blastp's score.
It is because Blastp doesn't require exact matches of eight consecutive AAs and allows mismatches and gaps.  

For example,
```
Virus A: ...AAAAAAAA...RAAAAAAAK...AAAA-AAAA
Virus B: ...AAAAAAAA...LAAAAAAAL...AAAARAAAA
```
I guess Blastp can find 23 matches (8+7+8).
But Metabuli can find only the first 8 matches, which leads to a lower identity score.
K-mer based tools such as Metabuli and Kraken2 use exact matches of fixed-length k-mers mainly to improve speed, so some similarities are missed as in the example.

I hope it helps you to understand :)
