### ISSUE TITLE
Feature request: support non-GC[AF] accessions

### ISSUE THREAD

**Issue by schorlton-bugseq** [steineggerlab/Metabuli#60]
Hi! I went to try out Metabuli (v1.0.4) with a custom database (thanks for the great docs!) but hit an issue:

```
During processing /test/test.fasta, accession testaccession is not found in the mapping file. It is skipped.
```

Inspecting the code reveals what appears to me is that Metabuli requires accessions follow NCBI convention with `GCF_*` or `GCA_*` (https://github.com/steineggerlab/Metabuli/blob/1.0.4/src/workflow/add_to_library.cpp#L156-L157). If correct, would it be possible to add support for non-NCBI formatted accessions? I believe many other metagenomic tools have this capability which is helpful for custom databases.

Thanks for your consideration!

**Comment by jaebeom-kim** [comment]
Thank you for reaching out!

You can build DB with accessions not following NCBI convention.
To do so, a customized `*.accession2taxid` file should be provided along with proper NCBI style taxonomy dump files.
`*.accession2taxid` is a TSV file like below.

```
accession accession.version taxid gi
testaccession1 testaccession1.1 1234 0
testaccession1 testaccession1.1 1235 0
...
```
You can put any numbers in `gi` column because it is not used.
Also, it is not necessary to put version number, like below.
```
testaccession3 testaccesion3 1236 0
```

**Comment by jaebeom-kim** [comment]
I acknowledge that a guideline for building a DB with custom accessions isn't provided in the README.
Thank you for flagging this :)

**Comment by schorlton-bugseq** [comment]
Awesome! Thanks for the quick response and will close the issue.
