### ISSUE TITLE
Question regarding databases

### ISSUE THREAD

**Issue by stas-malavin** [steineggerlab/Metabuli#65]
Hi,

Could you please clarify—to build a database, do I need both nt and aa seqs, or does metabuli translate nucleotides by itself? If it translates, can I specify the translation table?

And the databases themselves are not MMSeqs2 databases, right?

Thank you

**Comment by jaebeom-kim** [comment]
Thank you for reaching out.
Nucleotide sequences are enough to build a DB.
Metabuli translates it to build DB.
You cannot specify the translation table.
The standard table is utilized for all.
Since it handles metagenomic data, query reads have to be translated with standard codons. To best match the query, reference DB is also built using standard table.

Metabuli DB and MMseqs2 DB are different.

Thanks again!

________________________________
From: Stas Malavin ***@***.***>
Sent: Tuesday, May 21, 2024 5:02:21 PM
To: steineggerlab/Metabuli ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [steineggerlab/Metabuli] Question regarding databases (Issue #65)


Hi,

Could you please clarify—to build a database, do I need both nt and aa seqs, or does metabuli translate nucleotides by itself? If it translates, can I specify the translation table?

And the databases themselves are not MMSeqs2 databases, right?

Thank you

**Comment by stas-malavin** [comment]
Thanks for the elaborated reply!
